name: release-please
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      release_created:
        description: "Set if the release has been created"
        value: ${{ jobs.release-please.outputs.release_created }}
      tag_name:
        description: "The tag name"
        value: ${{ jobs.release-please.outputs.tag_name }}
      major:
        description: "Number representing major semver value"
        value: ${{ jobs.release-please.outputs.major }}
      minor:
        description: "Number representing minor semver value"
        value: ${{ jobs.release-please.outputs.minor }}
      patch:
        description: "Number representing patch semver value"
        value: ${{ jobs.release-please.outputs.patch }}
      sha:
        description: "SHA that a GitHub release was tagged at"
        value: ${{ jobs.release-please.outputs.sha }}

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: github.repository == 'slawo/unifios-utilities-dnsmasq-update'
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
      major: ${{ steps.release-please.outputs.major }}
      minor: ${{ steps.release-please.outputs.minor }}
      patch: ${{ steps.release-please.outputs.patch }}
      sha: ${{ steps.release-please.outputs.sha }}

    steps:
      - name: release-please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/.release-please-config.json
          manifest-file: .github/.release-please-manifest.json
